apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mysecret-sops
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:SLkzJJsMPaPK,iv:BqALUXip/5rgdqc91paBQluEBC8TgTPL77TVilZnJM8=,tag:7J9ERUEskZLiGChxyVhPGQ==,type:str]
          stringData:
            PG_PASSWORD: ENC[AES256_GCM,data:4V0iWVFWEn4s7++f2f3nz8Ixmwg=,iv:b3iLhGBn0Yqgd6plp+GYHS2AwIRm48DQ4z8n5zRXhHQ=,tag:FZAMGdvKwa2wv54s5UI8hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19tfqxgdgx3fe96j8fyy0c65nsfj8ku8sl4ccfxnzpn3xpakylg5s8sgac7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcXZWVkFDMi9WemU3eFJY
            N3BvVGhxWGFJRkZ4djFqZ29JcGlvZWlCdFJFCnYxWHU0REZBZkVUTlZIWnU2U3VR
            RW51MURTVUg5UVByYmRGQTUyUk1JWk0KLS0tIDdEYWJ3VzVxUXpXdEtIeUo1dmE5
            anptN3BIdVlGN0RrRWVpVkpSeFMxeWcKc1HpvWTLDZtTFv2YFIojYhb2dWKTrjCL
            nhOB5kSiXKPs2aKiwU9iGLVuSKyJAvM44dJMF9ho9eGieMls++rOHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g867s7tcftkgkdraz3ezs8xk5c39x6l4thhekhp9s63qxz0m7cgs5kan9a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdS9IaWh3YUJ2eTJKZjBl
            bk0wRlhKUVUrdDVCUnRneUJkVnI4ZEQ2cTA0CkV3c1JLd2cwTUZTTG1zcFBCb05H
            Zk5YdDVBKzlxM0JtRzg1aGlwMnllWHMKLS0tIEVaSVFvMzllUmJBRTlmaFlyQ1Vn
            WEdOV2I2K1NyMllmOVZGaFNJNnVCeDAKpfb1HeqWMnQ8WvriZ+PVzBvh4WLFipi6
            eg5HKw26v1lr16s3Yl4rpI4Sg0iEu63Ca8z2LKLLNp/x7RBzUTZB2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qt7e329qjlhqsfsyxsvws56ukp2f9h0ktmj45atleqk0q406mfhstwnudv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SVZrWmF5MHphT3o2UWVy
            aFQ3eHJzQVpYaHhaMUNhRGkxNUpUbjZBNkNrCkJmM2xNQ084YSsreU1pY0xLRmM5
            WlM1citKMVErK2x6OC9KQ0hQMjdVQkkKLS0tIENqOTFHcEp1RER2Y1A1UEpUUFB3
            OFpFMlRYYmxGSXdraFVOTlg0OS9INTgKk0VSQWF+uxxmkJIiaVyusOY6COJkwsOa
            Zt7W6PgE1EeIkKbNWRyKJaVC5k6t2Y+U83jr4T+5Nt+1MEL9TopuUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-17T14:27:54Z"
    mac: ENC[AES256_GCM,data:zJh+n1b/IKhA2q0EYPejLLcvYhgKmRfNCgLbWhvCQa3NVtQ+usKSIbT2I1+15+lr0cpGuMzXpk+mFJLjkHthgiEpkOZWYhvkvqlOLPWti7J1OiE5MSbb4RmO+3N+7VAhFo6LT9eGhtDEjYH2IiEkg1oSHDTNbtX2XTPsVES1hbE=,iv:B90MEKLXRvTvndBSe8+Md34MQSOZxJfHn06FTuTwg94=,tag:J3bnC7JOvB6R8doZQKdwTQ==,type:str]
    pgp: []
    encrypted_suffix: Templates
    version: 3.8.1
